default_agent: agent
agents:
  agent:
    name: agent
    entrypoint: agent.py
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::290981915560:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-d4f0bc5a29
      execution_role_auto_create: false
      account: '290981915560'
      region: us-west-2
      ecr_repository: 290981915560.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agent-tGZTU328K1
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:290981915560:runtime/agent-tGZTU328K1
      agent_session_id: 9a6c430d-3906-44cc-b98e-74cc2d012583
    codebuild:
      project_name: bedrock-agentcore-agent-builder
      execution_role: arn:aws:iam::290981915560:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-d4f0bc5a29
      source_bucket: bedrock-agentcore-codebuild-sources-290981915560-us-west-2
    memory:
      mode: STM_ONLY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
